### ISSUE TITLE
اضافه کردن from به کانفیگ

### ISSUE THREAD

**Issue by mojtaba82** [Melipayamak/melipayamak-laravel#1]
اگه شماره خط رو به فایل کانفیگتون اضافه کنید که اگه کاربر این مقدار رو وارد نکنه این مقدار از فایل کانفیگ خونده بشه

**Comment by amhome** [comment]
سلام دوست عزیز
پیشنهاد خوبیه ولی بعضی کاربران در یک پروژه ممکنه از چند خط برای ارسال یا دریافت استفاده کنند در این صورت پیشنهاد کاربردی نیست. به همین خاطر ما به میل کاربر رها کردیم
